name: "Release / Publish"
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:        
      - v0.*
      - v1.*
      - v2.*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Conventional Releaser
      uses: james-d-elliott/conventional-releaser-action@v0.1.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
